import "./globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { ThemeContext, ThemeProvider } from "@/context/ThemeContext";
import { useContext } from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="h-screen px-36 py-12 w-full flex flex-col justify-between bg-zinc-800 text-white">
        <ThemeProvider>
          <Header />
          <main className="h-full py-10 overflow-auto">{children}</main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
